// Mocks generated by Mockito 5.4.6 from annotations
// in music_ibook_flutter/test/providers/lesson_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:file_picker/file_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:music_ibook_flutter/models/lesson.dart' as _i2;
import 'package:music_ibook_flutter/models/lesson_note.dart' as _i5;
import 'package:music_ibook_flutter/services/lesson_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMusicLesson_0 extends _i1.SmartFake implements _i2.MusicLesson {
  _FakeMusicLesson_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LessonService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonService extends _i1.Mock implements _i3.LessonService {
  MockLessonService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MusicLesson>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i2.MusicLesson>>.value(
              <_i2.MusicLesson>[],
            ),
          )
          as _i4.Future<List<_i2.MusicLesson>>);

  @override
  _i4.Future<List<_i2.MusicLesson>> getMine() =>
      (super.noSuchMethod(
            Invocation.method(#getMine, []),
            returnValue: _i4.Future<List<_i2.MusicLesson>>.value(
              <_i2.MusicLesson>[],
            ),
          )
          as _i4.Future<List<_i2.MusicLesson>>);

  @override
  _i4.Future<_i2.MusicLesson> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.MusicLesson>.value(
              _FakeMusicLesson_0(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i4.Future<_i2.MusicLesson>);

  @override
  _i4.Future<_i2.MusicLesson> create(_i2.MusicLesson? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#create, [lesson]),
            returnValue: _i4.Future<_i2.MusicLesson>.value(
              _FakeMusicLesson_0(this, Invocation.method(#create, [lesson])),
            ),
          )
          as _i4.Future<_i2.MusicLesson>);

  @override
  _i4.Future<_i2.MusicLesson> update(int? id, _i2.MusicLesson? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#update, [id, lesson]),
            returnValue: _i4.Future<_i2.MusicLesson>.value(
              _FakeMusicLesson_0(
                this,
                Invocation.method(#update, [id, lesson]),
              ),
            ),
          )
          as _i4.Future<_i2.MusicLesson>);

  @override
  _i4.Future<void> addNote(int? lessonId, _i5.LessonNote? note) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [lessonId, note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addNotesOneByOne(
    int? lessonId,
    List<_i5.LessonNote>? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNotesOneByOne, [lessonId, notes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveContent(_i2.MusicLesson? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#saveContent, [lesson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> uploadAudio(int? lessonId, _i6.PlatformFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [lessonId, file]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> publish(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNote(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [noteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllNotes(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotes, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
