// Mocks generated by Mockito 5.4.6 from annotations
// in music_ibook_flutter/test/screens/student_home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:file_picker/file_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:music_ibook_flutter/models/lesson.dart' as _i3;
import 'package:music_ibook_flutter/models/lesson_note.dart' as _i5;
import 'package:music_ibook_flutter/providers/auth_provider.dart' as _i8;
import 'package:music_ibook_flutter/providers/lesson_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LessonProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonProvider extends _i1.Mock implements _i2.LessonProvider {
  MockLessonProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  bool get teacherLessonsLoading =>
      (super.noSuchMethod(
            Invocation.getter(#teacherLessonsLoading),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.MusicLesson> get lessons =>
      (super.noSuchMethod(
            Invocation.getter(#lessons),
            returnValue: <_i3.MusicLesson>[],
          )
          as List<_i3.MusicLesson>);

  @override
  set loading(bool? value) => super.noSuchMethod(
    Invocation.setter(#loading, value),
    returnValueForMissingStub: null,
  );

  @override
  set teacherLessonsLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#teacherLessonsLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set error(String? value) => super.noSuchMethod(
    Invocation.setter(#error, value),
    returnValueForMissingStub: null,
  );

  @override
  set lessons(List<_i3.MusicLesson>? value) => super.noSuchMethod(
    Invocation.setter(#lessons, value),
    returnValueForMissingStub: null,
  );

  @override
  set current(_i3.MusicLesson? value) => super.noSuchMethod(
    Invocation.setter(#current, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadLessons() =>
      (super.noSuchMethod(
            Invocation.method(#loadLessons, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadTeacherLessons() =>
      (super.noSuchMethod(
            Invocation.method(#loadTeacherLessons, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.MusicLesson?> loadLesson(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadLesson, [id]),
            returnValue: _i4.Future<_i3.MusicLesson?>.value(),
          )
          as _i4.Future<_i3.MusicLesson?>);

  @override
  _i4.Future<_i3.MusicLesson?> saveLesson(_i3.MusicLesson? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#saveLesson, [lesson]),
            returnValue: _i4.Future<_i3.MusicLesson?>.value(),
          )
          as _i4.Future<_i3.MusicLesson?>);

  @override
  _i4.Future<bool> addNotesOneByOne(
    int? lessonId,
    List<_i5.LessonNote>? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNotesOneByOne, [lessonId, notes]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> saveContent(_i3.MusicLesson? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#saveContent, [lesson]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> uploadAudio(int? lessonId, _i6.PlatformFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [lessonId, file]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> publish(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [lessonId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteNote(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [noteId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteAllNotes(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotes, [lessonId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteLesson(int? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLesson, [lessonId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  set loading(bool? value) => super.noSuchMethod(
    Invocation.setter(#loading, value),
    returnValueForMissingStub: null,
  );

  @override
  set error(String? value) => super.noSuchMethod(
    Invocation.setter(#error, value),
    returnValueForMissingStub: null,
  );

  @override
  set token(String? value) => super.noSuchMethod(
    Invocation.setter(#token, value),
    returnValueForMissingStub: null,
  );

  @override
  set role(String? value) => super.noSuchMethod(
    Invocation.setter(#role, value),
    returnValueForMissingStub: null,
  );

  @override
  set fullName(String? value) => super.noSuchMethod(
    Invocation.setter(#fullName, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> register(
    String? fullName,
    String? email,
    String? password,
    String? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [fullName, email, password, role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateProfile(String? fullName, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [fullName, newPassword]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
