// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music_IBook_API.Models;

#nullable disable

namespace Music_IBook_API.Migrations
{
    [DbContext(typeof(MusicIBookDbContext))]
    [Migration("20260718204943_AddPolyphonicScoreMetadata")]
    partial class AddPolyphonicScoreMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Music_IBook_API.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Music_IBook_API.Models.LessonNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Chord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationBeat")
                        .HasColumnType("float");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lyric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Second")
                        .HasColumnType("float");

                    b.Property<int>("Staff")
                        .HasColumnType("int");

                    b.Property<double>("StartBeat")
                        .HasColumnType("float");

                    b.Property<int>("Velocity")
                        .HasColumnType("int");

                    b.Property<int>("Voice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonNotes");
                });

            modelBuilder.Entity("Music_IBook_API.Models.MusicLesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("KeySignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PracticeGuide")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.Property<string>("TheoryContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSignatureMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PracticeSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("float");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExam")
                        .HasColumnType("bit");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PracticeSessionDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExpectedNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("LessonNoteId")
                        .HasColumnType("bigint");

                    b.Property<long>("PracticeSessionId")
                        .HasColumnType("bigint");

                    b.Property<double>("PressedAtSecond")
                        .HasColumnType("float");

                    b.Property<string>("PressedNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonNoteId");

                    b.HasIndex("PracticeSessionId");

                    b.ToTable("PracticeSessionDetails");
                });

            modelBuilder.Entity("Music_IBook_API.Models.StudentLessonProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BestScore")
                        .HasColumnType("int");

                    b.Property<int>("CompletedNoteCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<double>("LastPositionSecond")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastStudiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId", "LessonId")
                        .IsUnique();

                    b.ToTable("StudentLessonProgresses");
                });

            modelBuilder.Entity("Music_IBook_API.Models.StudentNoteAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExpectedAtSecond")
                        .HasColumnType("float");

                    b.Property<string>("ExpectedNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrectPitch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrectTiming")
                        .HasColumnType("bit");

                    b.Property<string>("JudgeResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LessonNoteId")
                        .HasColumnType("bigint");

                    b.Property<double>("PlayedAtSecond")
                        .HasColumnType("float");

                    b.Property<string>("PlayedNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PracticeSessionId")
                        .HasColumnType("bigint");

                    b.Property<double>("TimingErrorMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LessonNoteId");

                    b.HasIndex("PracticeSessionId");

                    b.ToTable("StudentNoteAttempts");
                });

            modelBuilder.Entity("Music_IBook_API.Models.LessonNote", b =>
                {
                    b.HasOne("Music_IBook_API.Models.MusicLesson", "Lesson")
                        .WithMany("Notes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Music_IBook_API.Models.MusicLesson", b =>
                {
                    b.HasOne("Music_IBook_API.Models.AppUser", "Teacher")
                        .WithMany("LessonsCreated")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Music_IBook_API.Models.AppUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PracticeSession", b =>
                {
                    b.HasOne("Music_IBook_API.Models.MusicLesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_IBook_API.Models.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PracticeSessionDetail", b =>
                {
                    b.HasOne("Music_IBook_API.Models.LessonNote", "LessonNote")
                        .WithMany()
                        .HasForeignKey("LessonNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Music_IBook_API.Models.PracticeSession", "PracticeSession")
                        .WithMany("Details")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonNote");

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("Music_IBook_API.Models.StudentLessonProgress", b =>
                {
                    b.HasOne("Music_IBook_API.Models.MusicLesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_IBook_API.Models.AppUser", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Music_IBook_API.Models.StudentNoteAttempt", b =>
                {
                    b.HasOne("Music_IBook_API.Models.LessonNote", "LessonNote")
                        .WithMany("StudentNoteAttempts")
                        .HasForeignKey("LessonNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Music_IBook_API.Models.PracticeSession", "PracticeSession")
                        .WithMany("NoteAttempts")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonNote");

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("Music_IBook_API.Models.AppUser", b =>
                {
                    b.Navigation("LessonsCreated");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Music_IBook_API.Models.LessonNote", b =>
                {
                    b.Navigation("StudentNoteAttempts");
                });

            modelBuilder.Entity("Music_IBook_API.Models.MusicLesson", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Music_IBook_API.Models.PracticeSession", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("NoteAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
